ALTER TABLE leads ADD COLUMN address TEXT NULL;
ALTER TABLE leads ADD COLUMN city VARCHAR(100) NULL;
ALTER TABLE leads ADD COLUMN state VARCHAR(100) NULL;
ALTER TABLE leads ADD COLUMN country VARCHAR(100) NULL;
ALTER TABLE leads ADD COLUMN zip_code VARCHAR(20) NULL;
ALTER TABLE leads ADD COLUMN website VARCHAR(255) NULL;
ALTER TABLE leads ADD COLUMN description TEXT NULL;
